#!/bin/sh

# xinitrc runs automatically when you run startx.

# Load up all of our auto-run programs and other settings, this will be
# sourced from ~/.config/x11/xprofile unless it doesn't exist.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Sleep to ensure that everything is loaded, so that we don't have to
# reload the xresources stuff right away.
sleep 2
